name: CD

on: [ push, pull_request ]

env:
  REGISTRY: 'rg.nl-ams.scw.cloud'
  REPOSITORY: 'petprojects/dav-hut-planner/app'

jobs:
  build-and-push-container:
    name: Build and push container
    runs-on: ubuntu-latest
    steps:
      - name: Setup clj-kondo
        uses: DeLaGuardo/setup-clj-kondo@afc83dbbf4e7e32e04649e29dbf30668d30e9e3e
        with:
          version: '2021.06.18'
      - name: Prepare java
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@3.4
        with:
          # Install just one or all simultaneously
          cli: 1.10.3.822
      - name: Checkout source
        uses: actions/checkout@v1
#      - name: Run tests
#        run: ./bin/kaocha
      - name: Lint with clj-kondo
        run: clj-kondo --lint src
      - name: Determine version
        id: version
        uses: ./.github/actions/version-commit
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: nologin
          password: ${{ secrets.SCALEWAY_SECRET_KEY }}
          registry: ${{ env.REGISTRY }}
          repository: ${{ env.REPOSITORY }}
          tags: 'latest,${{ steps.version.outputs.version }}'

  # Deploy job only runs on master after containers are built successful
  migrate-and-deploy:
    name: Deploy application
    runs-on: ubuntu-latest
    needs: build-and-push-container
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout source
        uses: actions/checkout@v1

      - name: Determine version
        id: version
        uses: ./.github/actions/version-commit

      - name: Deploy to CapRover
        uses: ./.github/actions/caprover-deploy
        with:
          caprover_url: 'https://captain.lchthbr.xyz'
          password: ${{ secrets.CAPROVER_SECRET }}
          app_name: dav-hut-planner
          image_name: '${{ env.REGISTRY }}/${{ env.REPOSITORY}}:${{ steps.version.outputs.version }}'
